### ISSUE TITLE
How to compute C_i (detection_mat)?

### ISSUE THREAD

**Issue by iamlvm** [yu-lab-vt/CINDA#11]
C_{i,j}, C_{en}, C_{ex} are well discussed in the paper (how to compute it) but I do not know how you can compute C_i

In your paper, C_i = log(beta_i / (1-beta_i). From your example code, C_i is in range [-8, -6] => beta_i is in range [0.00025,  0.0025]. **This means the probability beta_i for detection x_i is approaching to zero**.

How can I set beta_i or C_i for each detection in my dataset?

**Comment by ccwang92** [comment]
Hi,

Beta_i indicates the probability that detection X_i is false positive. You can use various way to determine it. One common way is to get it from the detection confidence of your own detection algorithm. Or you can esimate the false positive rate of detections frame-wisely or data-wisely. 

Hope this helps solve your question.
Best,
