### ISSUE TITLE
Memory leak in pyCS2() return pointer

### ISSUE THREAD

**Issue by angelcarro** [yu-lab-vt/CINDA#12]
The returned pointer from pyCS2() function is never freed. I solved this problem by adding the following function to cinda_funcs.c : 

>void pyFreeTrackVec(price_t *track_vec) {
>  free(track_vec);
>} 

And then, in algo.py, at the end of mcc4mot():

>	_cinda.pyFreeTrackVec.argtypes = (ctypes.POINTER(ctypes.c_longlong), )
>	_cinda.pyFreeTrackVec.restype = None
>	_cinda.pyFreeTrackVec(track_vec)
>
>	return traj, cost

**Comment by ccwang92** [comment]
Hi whizmo,

Cool. Thank you very much. We will append this fix to our code.
