### ISSUE TITLE
lib_cinda_funcs.so error

### ISSUE THREAD

**Issue by feniris** [yu-lab-vt/CINDA#5]
WhenI try to run the notebook, I get the following error

lib_cinda_funcs.so is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f

**Comment by yu-lab-vt** [comment]
Hi feniris,

The .so file did not run on Windows. We re-compiled the c code to .dll file. Now it should be OK. 

Best,
