### ISSUE TITLE
how create detecton_mat.txt and transition_mat.txt?

### ISSUE THREAD

**Issue by lujunxin** [yu-lab-vt/CINDA#8]
It's a great project, but I have a problem running this project with my own data. If I have a data sequence and the detection results of the sequence, how can I create my own transition_ mat.txt and detecton_mat.txt.

**Comment by ccwang92** [comment]
Hi,

Thank you for your interest in CINDA. trasition_mat.txt and detecton_mat.txt are the four scores to build the circulation graph. The detailed explanation of the four scores is listed in Eq.10-11 here (https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9204816). The User Manual shows the format of these two txt files.

Practically, the score design is quite flexible and data-driven. You can use rule-based methods or supervised methods to obtain the scores for your own data.

Best,
